import 'antd/es/popconfirm/style';
import 'antd/es/message/style';
import 'antd/es/card/style';
import 'antd/es/table/style';
import 'antd/es/pagination/style';
import 'antd/es/select/style';
import 'antd/es/upload/style';
import 'antd/es/form/style';
import 'antd/es/input/style';
import 'antd/es/popover/style';
import 'antd/es/row/style';
import 'antd/es/col/style';
import 'antd/es/button/style';
import 'antd/es/spin/style';
import 'antd/es/tree/style';
//# sourceMappingURL=antdStyle.js.map
