import 'antd/es/table/style';
import 'antd/es/button/style';
import 'antd/es/form/style';
import 'antd/es/select/style';
import 'antd/es/input/style';
import 'antd/es/row/style';
import 'antd/es/col/style';
import 'antd/es/card/style';
import 'antd/es/icon/style';
import 'antd/es/date-picker/style';
import 'antd/es/message/style';
import 'antd/es/modal/style';
import 'antd/es/pagination/style';
import 'antd/es/descriptions/style';
import 'antd/es/spin/style';
//# sourceMappingURL=antdStyle.js.map
