import 'antd/es/button/style';
import 'antd/es/icon/style';
import 'antd/es/message/style';
import 'antd/es/modal/style';
import 'antd/es/upload/style';
import 'antd/es/list/style';
import 'antd/es/avatar/style';
import 'antd/es/checkbox/style';
//# sourceMappingURL=antdStyle.js.map
